// @generated by python/tools/calibrate_dspark_cost_profile.py; do not edit.
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_ID: &str =
    "glm53-exl3-k4-dflash2-1rtx4spark-400w-route-v1";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_SOURCE_SHA256: &str =
    "661e07768189ceaa84776026443433c3d248752b8b59526e23e26048323e8e94";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_TARGET_MODEL: &str =
    "wrldsuksgo2mars/GLM-5.3-EXL3-K4-v1";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_TARGET_REVISION: &str =
    "47af23347db743b4666d952e2eb48f2b01c3fede";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_DSPARK_MODEL: &str = "incoai/GLM-5.3-DFlash2";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_DSPARK_REVISION: &str =
    "425aa615ce320caac34400208b30808c8f14f76c";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_SPARKINFER_REVISION: &str =
    "4f2a7841cd931cba4f591fdf385e01c267518f9a";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_TOPOLOGY: &str =
    "1x-rtx-pro-6000-sm120+4x-gb10-sm121-tp4-exl3-k4-fp8-rdma";
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_POWER_LIMIT_WATTS: usize = 400;
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_MAX_CONCURRENCY: usize = 4;
pub(super) const GLM53_EXL3_K4_DFLASH2_COST_PROFILE_MAX_DRAFTS: usize = 7;
pub(super) static GLM53_EXL3_K4_DFLASH2_COST_PROFILE_MS: [&[(usize, f64)];
    GLM53_EXL3_K4_DFLASH2_COST_PROFILE_MAX_CONCURRENCY] = [
    &[
        (1, 50.7122), // route-standardized-corpus-mean
        (2, 74.2734), // route-standardized-corpus-mean
        (3, 91.6876), // route-standardized-corpus-mean
        (4, 104.36),  // route-standardized-corpus-mean
        (5, 110.991), // startup-sweep-fallback
        (6, 120.652), // route-standardized-corpus-mean
        (7, 131.235), // startup-sweep-fallback
        (8, 131.724), // startup-sweep-fallback
    ],
    &[
        (2, 69.099),   // startup-sweep-fallback
        (3, 86.249),   // startup-sweep-fallback
        (4, 97.161),   // startup-sweep-fallback
        (5, 106.962),  // startup-sweep-fallback
        (6, 114.986),  // startup-sweep-fallback
        (7, 121.393),  // startup-sweep-fallback
        (8, 121.393),  // startup-sweep-fallback
        (9, 123.901),  // startup-sweep-fallback
        (10, 125.656), // startup-sweep-fallback
        (11, 132.049), // startup-sweep-fallback
        (12, 144.819), // route-standardized-corpus-mean
        (13, 147.033), // startup-sweep-fallback
        (14, 148.752), // startup-sweep-fallback
        (15, 149.867), // startup-sweep-fallback
        (16, 150.101), // startup-sweep-fallback
    ],
    &[
        (3, 105.207),  // startup-sweep-fallback
        (4, 121.348),  // startup-sweep-fallback
        (5, 134.817),  // startup-sweep-fallback
        (6, 148.226),  // startup-sweep-fallback
        (7, 157.575),  // startup-sweep-fallback
        (8, 166.154),  // startup-sweep-fallback
        (9, 176.78),   // startup-sweep-fallback
        (10, 176.832), // startup-sweep-fallback
        (11, 181.201), // startup-sweep-fallback
        (12, 182.568), // startup-sweep-fallback
        (13, 184.628), // startup-sweep-fallback
        (14, 186.366), // startup-sweep-fallback
        (15, 188.246), // startup-sweep-fallback
        (16, 193.63),  // startup-sweep-fallback
        (17, 196.275), // startup-sweep-fallback
        (18, 198.67),  // startup-sweep-fallback
        (19, 199.821), // startup-sweep-fallback
        (20, 200.716), // startup-sweep-fallback
        (21, 202.004), // startup-sweep-fallback
        (22, 205.25),  // startup-sweep-fallback
        (23, 208.734), // startup-sweep-fallback
        (24, 209.758), // startup-sweep-fallback
    ],
    &[
        (4, 127.514),  // startup-sweep-fallback
        (5, 144.488),  // startup-sweep-fallback
        (6, 157.234),  // startup-sweep-fallback
        (7, 168.82),   // startup-sweep-fallback
        (8, 181.045),  // startup-sweep-fallback
        (9, 193.683),  // startup-sweep-fallback
        (10, 201.451), // startup-sweep-fallback
        (11, 210.406), // startup-sweep-fallback
        (12, 219.398), // startup-sweep-fallback
        (13, 224.365), // startup-sweep-fallback
        (14, 226.367), // startup-sweep-fallback
        (15, 231.228), // startup-sweep-fallback
        (16, 233.67),  // startup-sweep-fallback
        (17, 237.125), // route-standardized-corpus-mean
        (18, 241.51),  // startup-sweep-fallback
        (19, 247.864), // route-standardized-corpus-mean
        (20, 251.898), // startup-sweep-fallback
        (21, 255.554), // startup-sweep-fallback
        (22, 259.058), // startup-sweep-fallback
        (23, 262.027), // startup-sweep-fallback
        (24, 264.061), // route-standardized-corpus-mean
        (25, 267.296), // startup-sweep-fallback
        (26, 270.693), // startup-sweep-fallback
        (27, 271.592), // startup-sweep-fallback
        (28, 274.064), // startup-sweep-fallback
        (29, 275.352), // startup-sweep-fallback
        (30, 276.45),  // startup-sweep-fallback
        (31, 276.482), // startup-sweep-fallback
        (32, 277.548), // startup-sweep-fallback
    ],
];
