pub const DEFAULT_MODEL_ID: &str = "lukealonso/GLM-5.2-NVFP4";
pub const NVIDIA_MODEL_ID: &str = "nvidia/GLM-5.2-NVFP4";
pub const EXL3_MODEL_ID: &str = "wrldsuksgo2mars/GLM-5.2-EXL3-K3-calibrated-v1";
pub const GLM53_EXL3_MODEL_ID: &str = "wrldsuksgo2mars/GLM-5.3-EXL3-K4-v1";
pub const SUPPORTED_MODEL_IDS: [&str; 4] = [
    DEFAULT_MODEL_ID,
    NVIDIA_MODEL_ID,
    EXL3_MODEL_ID,
    GLM53_EXL3_MODEL_ID,
];
pub const COORDINATOR_HOST: &str = "coordinator";
pub const EXPERT_HOSTS: [&str; 4] = ["spark-0", "spark-1", "spark-2", "spark-3"];
pub const GLM52_HIDDEN_SIZE: usize = 6144;
pub const GLM52_NUM_HIDDEN_LAYERS: usize = 78;
pub const GLM52_NUM_MTP_LAYERS: usize = 1;
pub const GLM52_MTP_LAYER_ID: usize = GLM52_NUM_HIDDEN_LAYERS;
pub const GLM52_TOTAL_LAYERS_WITH_MTP: usize = GLM52_NUM_HIDDEN_LAYERS + GLM52_NUM_MTP_LAYERS;
pub const GLM52_FIRST_K_DENSE_REPLACE: usize = 3;
pub const GLM52_ROUTED_EXPERTS: usize = 256;
pub const GLM52_TOP_K: usize = 8;
pub const GLM52_MOE_INTERMEDIATE_SIZE: usize = 2048;
pub const GLM52_ROUTED_SCALING_FACTOR: f32 = 2.5;
pub const GLM52_HIDDEN_BF16_BYTES: usize = GLM52_HIDDEN_SIZE * 2;
pub const GLM52_MLA_KV_LORA_RANK: usize = 512;
pub const GLM52_MLA_QK_ROPE_HEAD_DIM: usize = 64;
pub const GLM52_MLA_ROPE_THETA: f32 = 8_000_000.0;
pub const GLM52_MLA_FP8_DS_SCALE_BYTES_PER_TOKEN: usize = 16;
pub const GLM52_MLA_FP8_DS_BYTES_PER_TOKEN: usize = GLM52_MLA_KV_LORA_RANK
    + GLM52_MLA_FP8_DS_SCALE_BYTES_PER_TOKEN
    + GLM52_MLA_QK_ROPE_HEAD_DIM * 2;
pub const GLM52_MLA_MXFP4_BLOCK_SIZE: usize = 16;
pub const GLM52_MLA_MXFP4_CODE_BYTES_PER_TOKEN: usize = GLM52_MLA_KV_LORA_RANK / 2;
pub const GLM52_MLA_MXFP4_SCALE_BYTES_PER_TOKEN: usize =
    GLM52_MLA_KV_LORA_RANK / GLM52_MLA_MXFP4_BLOCK_SIZE;
pub const GLM52_MLA_MXFP4_PADDING_BYTES_PER_TOKEN: usize = 16;
pub const GLM52_MLA_MXFP4_DS_BYTES_PER_TOKEN: usize = GLM52_MLA_MXFP4_CODE_BYTES_PER_TOKEN
    + GLM52_MLA_MXFP4_SCALE_BYTES_PER_TOKEN
    + GLM52_MLA_MXFP4_PADDING_BYTES_PER_TOKEN
    + GLM52_MLA_QK_ROPE_HEAD_DIM * 2;
pub const GLM52_DSA_INDEXER_LAYERS: usize = 21;
pub const GLM52_DSA_INDEXER_LAYER_IDS: [usize; GLM52_DSA_INDEXER_LAYERS] = [
    0, 1, 2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
];
pub const GLM52_DSA_INDEXER_LAYER_IDS_WITH_MTP: [usize;
    GLM52_DSA_INDEXER_LAYERS + GLM52_NUM_MTP_LAYERS] = [
    0, 1, 2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78,
];
pub const GLM52_DSA_INDEX_HEAD_DIM: usize = 128;
pub const GLM52_COMPRESSED_MAIN_MLA_BF16_BYTES_PER_TOKEN: usize =
    GLM52_NUM_HIDDEN_LAYERS * (GLM52_MLA_KV_LORA_RANK + GLM52_MLA_QK_ROPE_HEAD_DIM) * 2;
pub const GLM52_COMPRESSED_DSA_BF16_BYTES_PER_TOKEN: usize =
    GLM52_DSA_INDEXER_LAYERS * GLM52_DSA_INDEX_HEAD_DIM * 2;
pub const GLM52_COMPRESSED_KV_BF16_BYTES_PER_TOKEN: usize =
    GLM52_COMPRESSED_MAIN_MLA_BF16_BYTES_PER_TOKEN + GLM52_COMPRESSED_DSA_BF16_BYTES_PER_TOKEN;
pub const GLM52_EXPANDED_DEBUG_KV_BF16_BYTES_PER_TOKEN: usize =
    GLM52_NUM_HIDDEN_LAYERS * 2 * GLM52_HIDDEN_SIZE * 2;

#[cfg(test)]
mod tests {
    use super::{GLM53_EXL3_MODEL_ID, SUPPORTED_MODEL_IDS};

    #[test]
    fn production_model_allowlist_includes_glm53_exl3_k4() {
        assert!(SUPPORTED_MODEL_IDS.contains(&GLM53_EXL3_MODEL_ID));
        assert_eq!(GLM53_EXL3_MODEL_ID, "wrldsuksgo2mars/GLM-5.3-EXL3-K4-v1");
    }
}
